// `harnessgap init claude` installer. Writes three artifacts under <cwd>/.claude/
// so the trip-gated Stop hook lands on a user's machine:
//   1. a fail-open wrapper script (`.claude/harnessgap-stop-hook.js`)
//   2. an idempotent settings.json Stop-array merge (`.claude/settings.json`)
//   3. the `/reflect` agent-guidance command (`.claude/commands/reflect.md`)
//
// Detection path (`reflect` / `runReflect`) is untouched — this module only
// installs. Constraints: no runtime deps, only `node:fs` + `node:path`. The
// wrapper's `child_process` use lives inside the emitted string (a runtime
// artifact under .claude/, not part of src/'s egress surface).

import { dirname, join } from 'node:path';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

/**
 * Absolute path to the published CLI binary (`dist/cli.js`), resolved from the
 * package root. Anchored at `package.json` (the way `src/cli.ts` anchors its
 * `../package.json` URL) rather than a fixed `../cli.js` offset: this file
 * lives at `src/init/claude.ts` under the test runner and at
 * `dist/init/claude.js` as the installed bin, and only the package root is a
 * stable anchor for `dist/cli.js` in both. `decodeURIComponent` keeps paths
 * with spaces valid (URL pathname %-encodes them).
 */
const PKG_URL = new URL('../../package.json', import.meta.url);
const PKG_ROOT = dirname(decodeURIComponent(PKG_URL.pathname));
export const CLI_PATH = join(PKG_ROOT, 'dist', 'cli.js');

/** Relative locations of the three artifacts under <cwd>/.claude/. */
const WRAPPER_REL = join('.claude', 'harnessgap-stop-hook.js');
const SETTINGS_REL = join('.claude', 'settings.json');
const COMMAND_REL = join('.claude', 'commands', 'reflect.md');

/**
 * Build the fail-open Stop-hook wrapper source for a given CLI path. Exported
 * (rather than inlined in {@link initClaude}) so tests can bake in a bogus
 * `cliPath` and exercise the missing-binary / spawn-failure fail-open path
 * (`{}` + exit 0) without string surgery on the emitted file. Contract:
 * - read all stdin, JSON.parse (defensive: malformed → {}).
 * - `stop_hook_active === true` → `{}`, exit 0 (short-circuit, no spawn).
 * - missing/empty `transcript_path` → `{}`, exit 0 (no spawn).
 * - spawn `node <cliPath> reflect --transcript <tp> --format hook-stop`;
 *   on spawn error / non-zero exit / empty stdout → `{}`, exit 0.
 * - otherwise forward the binary's stdout verbatim, exit 0.
 * - top-level try/catch so any throw → `{}`, exit 0.
 *
 * Load-bearing fail-open: Claude Code treats a non-zero exit or a missing
 * command as a blocking hook error, so every fault path must synthesize `{}`
 * and exit 0 rather than propagate.
 */
export function buildWrapperSource(opts: { cliPath: string }): string {
  const { cliPath } = opts;
  return `#!/usr/bin/env node
// Auto-generated by \`harnessgap init claude\`. Fail-open Claude Code Stop hook.
// Any fault short-circuits to {} so the harness never reads a wrapper error as
// a block. The block decision itself is computed by \`harnessgap reflect\`.
var fs = require('fs');
var CLI = ${JSON.stringify(cliPath)};
// emit() writes the payload then exits inside stdout's flush callback so piped
// output is never truncated by process.exit (mirrors src/cli.ts). It is the
// ONLY exit path: each fail-open decision flows into a terminal emit() call, so
// nothing runs after a decision is made (no fall-through into the spawn path).
function emit(payload) { process.stdout.write(payload, () => process.exit(0)); }
try {
  var raw = fs.readFileSync(0, 'utf8');
  var payload = {};
  try { payload = JSON.parse(raw); } catch (e) { payload = {}; }
  // Skip the spawn entirely on the two short-circuits: an already-active hook,
  // or a missing/empty transcript_path.
  var transcript = payload && payload.transcript_path;
  var doSpawn =
    !(payload && payload.stop_hook_active === true) &&
    typeof transcript === 'string' && transcript.length > 0;
  var result = null;
  if (doSpawn) {
    var cp = require('child_process');
    result = cp.spawnSync(
      process.execPath,
      [CLI, 'reflect', '--transcript', transcript, '--format', 'hook-stop'],
      { input: '', encoding: 'utf8' }
    );
  }
  // Spawn skipped, or spawn error / non-zero exit / empty stdout → fail open.
  if (result && !result.error && result.status === 0 && result.stdout) {
    emit(result.stdout);
  } else {
    emit('{}\\n');
  }
} catch (e) {
  emit('{}\\n');
}
`;
}

/**
 * The `/reflect` agent-guidance prompt. No detection logic — instructs the
 * agent to obtain a `ReflectFinding`, fill one `ReflectFrame` (cost tied to a
 * top signal, missing context, one change with a verified repo-relative path),
 * present it, offer to draft in-session, and emit `kind:"none"` when clean.
 */
const COMMAND_SOURCE = `# /reflect

Reflect on a session that showed harness friction. This command runs **no
detection itself** — it guides you through producing one concrete
\`ReflectFrame\` from an already-computed \`ReflectFinding\`.

## When triggered by a Stop-hook block

If you are here because a Stop hook returned \`{ "decision": "block", "reason" }\`,
that \`reason\` already carries the finding summary (top friction areas + active
signals). Use it directly — do **not** re-invoke the binary.

## Otherwise, obtain the finding

Run the detector on the most recent finished session for this repo:

\`\`\`
harnessgap reflect --latest --repo . --json
\`\`\`

Read the emitted \`ReflectFinding\`. If \`trip\` is \`false\`, skip to
"Clean session" below.

## Fill exactly one ReflectFrame

- **cost** — the friction cost this session, tied to the finding's top signal
  (a failure streak, a reread loop, oscillating edits, or abandonment). One
  sentence.
- **missing** — the context that would have helped avoid the friction (a doc, a
  type annotation, a missing test, an absent tool result). One sentence.
- **change** — one proposed harness change:
  - \`target_path\` — a repo-relative path to add or improve.
  - \`kind\` — \`add\` | \`improve\` | \`none\`.
  - \`rationale\` — why this change targets the observed cost.
- **path_verified** — before presenting, confirm \`target_path\` (or its **parent
  directory** for an \`add\`) exists via a Read or Glob. Set \`true\` only when
  confirmed; \`false\` if you could not verify it.

## Present + offer

Present the recommendation concisely: cost → change → rationale. Then offer to
draft the change in-session (sketch the file or edit) if the user wants.

## Clean session

If \`trip === false\` or the session was clean, say so briefly and emit a frame
with \`change.kind: "none"\` (no harness change needed). Do not invent friction.
`;

// --- settings.json merge (idempotent, preserves user data) ---

interface HookEntry {
  type?: string;
  command?: string;
  [k: string]: unknown;
}
interface StopEntry {
  matcher?: string;
  hooks?: HookEntry[];
  [k: string]: unknown;
}

function isStopEntry(v: unknown): v is StopEntry {
  return !!v && typeof v === 'object' && !Array.isArray(v);
}

/**
 * Ensure \`hooks.Stop\` contains exactly one entry whose command is \`node <wrapper>\`,
 * deduped by command string. Reads defensively (missing/invalid → \`{}\`), preserves
 * every other top-level key and every other Stop entry (including user hooks that
 * share an entry with the harnessgap command).
 */
function mergeStopHook(
  raw: Record<string, unknown>,
  wrapperPath: string,
): Record<string, unknown> {
  const settings: Record<string, unknown> = { ...raw };
  const cmd = `node ${wrapperPath}`;

  const hooksVal = settings.hooks;
  const hooks: Record<string, unknown> =
    isStopEntry(hooksVal) ? { ...hooksVal } : {};
  const stopRaw = Array.isArray(hooks.Stop) ? (hooks.Stop as unknown[]) : [];

  const kept: StopEntry[] = [];
  for (const entry of stopRaw) {
    if (!isStopEntry(entry) || !Array.isArray(entry.hooks)) {
      // Unknown shape — preserve untouched.
      kept.push(entry as StopEntry);
      continue;
    }
    const filtered = entry.hooks.filter((h) => !isStopEntry(h) || h.command !== cmd);
    if (filtered.length === 0 && entry.hooks.length > 0) {
      // The entry consisted solely of the harnessgap command — drop (re-added fresh).
      continue;
    }
    kept.push({ ...entry, hooks: filtered });
  }
  kept.push({ matcher: '', hooks: [{ type: 'command', command: cmd }] });

  hooks.Stop = kept;
  settings.hooks = hooks;
  return settings;
}

/** Options for {@link initClaude}. */
export interface InitClaudeOpts {
  /** Target working directory; artifacts land under <cwd>/.claude/. */
  cwd: string;
}

/** Result of {@link initClaude}: absolute paths of the three written artifacts. */
export interface InitClaudeResult {
  wrapperPath: string;
  settingsPath: string;
  commandPath: string;
}

/**
 * Install (or refresh) the three Claude Code artifacts under \`opts.cwd/.claude/\`.
 * Idempotent: the wrapper + command are rewritten on every call, and the
 * \`hooks.Stop\` array is merged so the harnessgap entry appears exactly once
 * with all user settings preserved. Returns the absolute artifact paths.
 */
export function initClaude(opts: InitClaudeOpts): InitClaudeResult {
  const wrapperPath = join(opts.cwd, WRAPPER_REL);
  const settingsPath = join(opts.cwd, SETTINGS_REL);
  const commandPath = join(opts.cwd, COMMAND_REL);

  // Ensure .claude/ and .claude/commands/ exist.
  mkdirSync(dirname(wrapperPath), { recursive: true });
  mkdirSync(dirname(commandPath), { recursive: true });

  // Wrapper + command are refreshed verbatim each run.
  writeFileSync(wrapperPath, buildWrapperSource({ cliPath: CLI_PATH }), 'utf8');
  writeFileSync(commandPath, COMMAND_SOURCE, 'utf8');

  // settings.json: read → parse-or-default → merge → write (pretty-printed).
  let raw: Record<string, unknown> = {};
  try {
    const text = readFileSync(settingsPath, 'utf8');
    const parsed = JSON.parse(text);
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
      raw = parsed as Record<string, unknown>;
    }
  } catch {
    // missing or invalid → start fresh; never throw on user's broken file.
  }
  const merged = mergeStopHook(raw, wrapperPath);
  writeFileSync(settingsPath, `${JSON.stringify(merged, null, 2)}\n`, 'utf8');

  return { wrapperPath, settingsPath, commandPath };
}
